Repository GIScience/oshdb, pull requests merged in 2019-07, with the labels that each got.

#185 more robust multipolygon geometry building with invalid outer rings
  CHANGELOG.md
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderMultipolygonInvalidOutersTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderRelationOuterDirectionsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderRelationTypeNotMultipolygonTest.java
  oshdb-util/src/test/resources/relations/invalid-outer-ring.osm
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osm/OSMWay.java
Labels: bug, performance

#183 fix calculation of insertIds
  CHANGELOG.md
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/index/XYGrid.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/index/XYGridTest.java
Labels: bug

#192 Fix Javadoc, remove orphaned E_NODE2WAY, …
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapAggregator.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducerAggregations.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/object/OSMContribution.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/util/OSHDB2Ignite.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/TableNames.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastInPolygon.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/index/XYGrid.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osm/OSMMember.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/util/CellId.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/index/XYGridTest.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/index/XYGridTreeTest.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/osm/OSMMemberTest.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/osm/OSMNodeTest.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/osm/OSMRelationTest.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/osm/OSMWayTest.java
  oshdb/src/test/java/org/heigit/bigspatialdata/oshdb/util/CellIdTest.java
Labels: CI, bug, documentation

#181 Releases are deployed to central
  Jenkinsfile
  pom.xml
Labels: CI
