Repository GIScience/oshdb, pull requests merged in 2019-03, with the labels that each got.

#111 speedup building of geometries from osm entities
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
Labels: performance

#130 switch to enlarged grid cells
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/index/XYGrid.java
Labels: enhancement

#140 upgrade checkstyle
  pom.xml
Labels: dependencies

#141 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, enhancement, user experience

#144 Update Jenkinsfile
  Jenkinsfile
Labels: CI

#142 Updating Changelog (addressing #88)
  CHANGELOG.md
Labels: documentation

#139 Documentation restructuring, update and cleanup
  README.md
  documentation/README.md
  documentation/first-steps/BuildingAreaHeidelberg.png
  documentation/first-steps/OSHDBApiTutorial.java
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/README.md
  documentation/manual/aggregation.md
  documentation/manual/api.md
  documentation/manual/data-model.md
  documentation/manual/data-model.svg
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
  documentation/oshdb-api-tutorial/OSHDBApiTutorial.java
  documentation/oshdb-api-tutorial/README.md
  documentation/oshdb-api-tutorial/aggregation-settings.md
  documentation/oshdb-api-tutorial/entity-filters.md
  documentation/oshdb-api-tutorial/example-pom.xml
  documentation/oshdb-api-tutorial/mandatory-settings.md
  documentation/oshdb-api-tutorial/map.md
  documentation/oshdb-api-tutorial/multiple-maps-and-filters.md
  documentation/oshdb-api-tutorial/preparation.md
  documentation/oshdb-api-tutorial/reduce.md
  documentation/oshdb-api-tutorial/result-filters.md
  documentation/oshdb-api-tutorial/result-handling.md
Labels: help wanted, user experience

#151 fix typos in changelog
  CHANGELOG.md
Labels: documentation
