Repository GIScience/oshdb, pull requests merged in 2019-05, with the labels that each got.

#172 fix calculation of areas of polygons with inner rings
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/Geo.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/GeoTest.java
Labels: bug

#176 fix typo in contribution guidelines.
  CONTRIBUTING.md
Labels: documentation

#174 update documentation to 0.5.1 release
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation

#115 Add more tests for building geometries from OSM entities
  .gitignore
  Jenkinsfile
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/backend/MapReducerIgniteLocalPeek.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/backend/MapReducerIgniteScanQuery.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPolygonOperations.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/BaseTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/DefaultTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/InvertedHashSet.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/TagInterpreter.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateAllTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionNotOsmTypeSpecificTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionRelationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionTypeNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampNotOsmTypeSpecificTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsRelationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/helpers/GridOSHFactory.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilderTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/FakeTagInterpreter.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/FakeTagInterpreterAreaAlways.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/FakeTagInterpreterAreaMultipolygonAllOuters.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/FakeTagInterpreterAreaNever.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/OSMXmlReaderTagInterpreter.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/TimestampParser.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/incomplete/OSHDBGeometryBuilderTestPolygonIncompleteDataTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/incomplete/OSHDBGeometryBuilderTestWayIncompleteDataTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataRelationNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataRelationTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData1xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData3xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderTestRelationOuterDirectionsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderTestRelationTypeNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/OSMXmlReader.java
  oshdb-util/src/test/resources/different-timestamps/node.osm
  oshdb-util/src/test/resources/different-timestamps/not-osm-type-specific.osm
  oshdb-util/src/test/resources/different-timestamps/polygon.osm
  oshdb-util/src/test/resources/different-timestamps/type-not-multipolygon.osm
  oshdb-util/src/test/resources/different-timestamps/way.osm
  oshdb-util/src/test/resources/incomplete-osm/polygon.osm
  oshdb-util/src/test/resources/incomplete-osm/way.osm
  oshdb-util/src/test/resources/osm-testdata/all.osm
  oshdb-util/src/test/resources/osm-testdata/readme.md.txt
  oshdb-util/src/test/resources/relations/outer-directions.osm
  oshdb-util/src/test/resources/relations/relationTypeNotMultipolygon.osm
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osh/OSHRelation.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osm/OSMRelation.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osm/OSMWay.java
Labels: moved from gitlab, unit tests
