Repository GIScience/oshdb, pull requests merged in 2020-11, with the labels that each got.

#249 dedicated handling of touching inner rings in multipoygons
  CHANGELOG.md
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderMultipolygonInvalidOutersTest.java
Labels: performance

#276 include test directory in checkstyle
  .idea/checkstyle-idea.xml
  pom.xml
Labels: CI, code quality

#267 CellIterator class: add missing javadoc and fix code style issues found by checkstyle
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java
Labels: code quality, waiting for review

#265 fixes #259 allowing trailing Z for all variants of time parts
  CHANGELOG.md
  documentation/manual/filters.md
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/cli/validator/TimeValidity.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParser.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampException.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampIllegalArgumentException.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampParseException.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestamps.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilderTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/TimestampParser.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampsTest.java
Labels: breaking, code quality, user experience, waiting for review

#278 update link to our checkstyle rules file
  config/ide/README.md
Labels: documentation

#275 fix checkstyle warnings in oshdb-util
  .idea/checkstyle-idea.xml
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/TableNames.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/LazyEvaluatedContributionTypes.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/LazyEvaluatedObject.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/exceptions/OSHDBKeytablesNotFoundException.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxInPolygon.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxOutsidePolygon.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastInPolygon.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPointInPolygon.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPolygonOperations.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/BaseTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/DefaultTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/OSMTag.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/TagTranslator.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampInterval.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampList.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateAllTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionNotOsmTypeSpecificTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionRelationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionTypeNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampNotOsmTypeSpecificTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsRelationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/helpers/GridOSHFactory.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/GeoTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilderTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxInPolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxOutsidePolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPointInPolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPolygonOperationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/FakeTagInterpreter.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/OSMXmlReaderTagInterpreter.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/TimestampParser.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/incomplete/OSHDBGeometryBuilderTestPolygonIncompleteDataTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/incomplete/OSHDBGeometryBuilderTestWayIncompleteDataTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataRelationNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataRelationTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData1xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData3xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderMultipolygonInvalidOutersTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderRelationOuterDirectionsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderRelationTypeNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/TagTranslatorTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/TimestampFormatterTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/MutableOSMEntity.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/MutableOSMNode.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/OSMXmlReader.java
  pom.xml
Labels: code quality, waiting for review

#280 add DOI badge and how to cite
  README.md
Labels: documentation

#253 ohsome filters
  CHANGELOG.md
  documentation/manual/filters.md
  documentation/manual/map-reduce.md
  oshdb-api/pom.xml
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapAggregator.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/test/java/org/heigit/bigspatialdata/oshdb/api/tests/TestLambdaFilter.java
  oshdb-api/src/test/java/org/heigit/bigspatialdata/oshdb/api/tests/TestOSMDataFilters.java
  oshdb-api/src/test/java/org/heigit/bigspatialdata/oshdb/api/tests/TestOhsomeFilter.java
Labels: enhancement, user experience, waiting for review

#281 reduce usage of numeric generics in MapReducer class
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/generic/WeightedValue.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapAggregator.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MutableWeightedDouble.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/PayloadWithWeight.java
  oshdb-api/src/test/java/org/heigit/bigspatialdata/oshdb/api/tests/TestHelpersOSMContributionView.java
  oshdb-api/src/test/java/org/heigit/bigspatialdata/oshdb/api/tests/TestHelpersOSMEntitySnapshotView.java
Labels: code quality

#284 documentation: switch links to https where possible
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/database-backends.md
  documentation/manual/installation.md
Labels: documentation
