Repository GIScience/oshdb, pull requests merged in 2020-12, with the labels that each got.

#287 improve performance of building multipolygons with a huge number of member ways
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
Labels: performance

#291 remove references to repo.heigit.org as this is not needed anymore
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/installation.md
Labels: documentation

#293 release notes for 0.6.0-RC1
  CHANGELOG.md
Labels: documentation

#283 fix checkstyle issues and other in oshdb-util
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/LazyEvaluatedObject.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxInPolygon.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxOutsidePolygon.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPolygonOperations.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/BaseTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/DefaultTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/OSMRole.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/OSMTagKey.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateAllTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionNotOsmTypeSpecificTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionRelationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionTypeNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByContributionWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampNotOsmTypeSpecificTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsRelationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateByTimestampsWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/helpers/GridOSHFactory.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilderTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxInPolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastBboxOutsidePolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPointInPolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/fip/FastPolygonOperationsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/OSMXmlReaderTagInterpreter.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/helpers/TimestampParser.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/incomplete/OSHDBGeometryBuilderTestPolygonIncompleteDataTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/incomplete/OSHDBGeometryBuilderTestWayIncompleteDataTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataNodesTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataRelationNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataRelationTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataWaysTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData1xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData3xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderMultipolygonInvalidOutersTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/relations/OSHDBGeometryBuilderRelationTypeNotMultipolygonTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/OSHDBTimestampsTest.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/MutableOSMEntity.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/OSMXmlReader.java
Labels: code quality, waiting for review

#294 make example in first-steps tutorial actually compile by fixing imports
  documentation/first-steps/OSHDBApiTutorial.java
  documentation/first-steps/example-pom.xml
Labels: documentation

#298 Remove java 8 properties from first-steps example
  documentation/first-steps/OSHDBApiTutorial.java
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
Labels: documentation

#299 remove java 8 references from documentation
  documentation/manual/api.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapAggregator.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducerAggregations.java
Labels: documentation, waiting for review

#300 java 1.8 version in installation.md fixed
  documentation/manual/installation.md
Labels: documentation, waiting for review

#301 upgrade to ohsome filter version 1.4.1
  oshdb-api/pom.xml
Labels: dependencies

#303 release notes and final doc updates for 0.6.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation

#306 integrate ohsome filter
  CHANGELOG.md
  oshdb-api/pom.xml
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapAggregator.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducerSettings.java
  oshdb-api/src/test/java/org/heigit/bigspatialdata/oshdb/api/tests/TestOhsomeFilter.java
  oshdb-filter/README.md
  oshdb-filter/pom.xml
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/AndOperator.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/BinaryOperator.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/ConstantFilter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/Filter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/FilterExpression.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/FilterParser.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterArea.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterLength.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryTypeFilter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/IdFilterEquals.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/IdFilterEqualsAnyOf.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/IdFilterNotEquals.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/IdFilterRange.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/NegatableFilter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/OrOperator.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterAnyOf.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterEquals.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterEqualsAny.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterEqualsAnyOf.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterNotEquals.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterNotEqualsAny.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TagFilterNotEqualsAnyOf.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/TypeFilter.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSHTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMGeometryTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/FilterByTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/FilterTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/NegateTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/NormalizeTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ParseTest.java
  oshdb-filter/src/test/resources/keytables.mv.db
  oshdb-filter/src/test/resources/log4j.properties
  pom.xml
Labels: dependencies

#310 simplify included maven repository
  pom.xml
Labels: dependencies, priority:low

#319 maxzoom is 14 not 15
  oshdb/src/main/java/org/heigit/ohsome/oshdb/OSHDB.java
Labels: performance, priority:high

#317 resolves #288 moving polygon-feature.json & uninterestingTags.json
  oshdb-util/src/main/resources/json/polygon-features.json
  oshdb-util/src/main/resources/json/uninterestingTags.json
Labels: clean-up

#318 removing resource sql/grid.sql
  oshdb/src/main/resources/sql/grid.sql
Labels: clean-up

#322 make ohsome filters work with groupByEntity queries
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java
Labels: bug

#323 fix javadoc links to method anchors
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducerSettings.java
Labels: documentation

#326 fix crash when relation references redacted way
  CHANGELOG.md
  oshdb/src/main/java/org/heigit/ohsome/oshdb/osh/OSHEntities.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java
Labels: bug

#328 release notes for 0.6.1 and 0.5.11
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation

#329 improve and align GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: clean-up, documentation
