Repository GIScience/oshdb, pull requests merged in 2020-10, with the labels that each got.

#271 upgrade ignite to version 2.9.0, prepare release 0.5.10
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
  pom.xml
Labels: waiting for review

#237 drop unused import statements
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/util/lambda/ConsumerUtil.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/OSHDBGeometryBuilder.java
Labels: code quality, priority:low

#233 most infer error resource-leak and null dereference fixes
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/object/OSMContribution.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/object/OSMEntitySnapshot.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/extract/Extract.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/extract/TypeStartFinder.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/extract/collector/KVFCollector.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/extract/collector/RoleCollector.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/load/Loader.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/load/LoaderKeyTables.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/load/LoaderNode.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/load/LoaderRelation.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/load/LoaderWay.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/load/handle/OSHDB2H2Handler.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/Transform.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/TransformerTagRoles.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/reader/TransformReader.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/reader/TransformRelationReaders.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/reader/TransformWayReaders.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/reader/TransfromNodeReaders.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/util/ExternalSort.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/util/long2long/SortedLong2LongMap.java
  oshdb-tool/oshpbf-parser/src/main/java/org/heigit/bigspatialdata/oshpbf/parser/pbf/PbfBlob.java
  oshdb-tool/oshpbf-parser/src/main/java/org/heigit/bigspatialdata/oshpbf/parser/rx/RxOshPbfReader.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/DefaultTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/TagTranslator.java
Labels: code quality, priority:low, waiting for review

#246 Cleanup tagtranslator
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/backend/MapReducerIgniteLocalPeek.java
  oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/transform/reader/TransformRelationReaders.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/taginterpreter/DefaultTagInterpreter.java
  oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/tagtranslator/TagTranslator.java
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/celliterator/IterateAllTest.java
Labels: code quality

#239 Removing UNKNOWN from OSMType, throw Exception instead!
  oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/xmlreader/OSMXmlReader.java
  oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osm/OSMType.java
Labels: code quality
