Repository GIScience/oshdb, pull requests merged in 2021-05, with the labels that each got.

#375 update to ohsome-parent 2.10
  .idea/checkstyle-idea.xml
  CHANGELOG.md
  Jenkinsfile
  oshdb-api/pom.xml
  pom.xml
Labels: CI, dependencies

#365 replace usage of a deprecated method
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
Labels: code quality

#376 add eclipse .checkstyle to gitignore
  .gitignore
Labels: code quality

#377 update to ohsome-parent 2.11
  .gitignore
  .idea/checkstyle-idea.xml
  Jenkinsfile
  pom.xml
Labels: CI, code quality

#379 change downloads links in documentation
  documentation/first-steps/README.md
  documentation/manual/database-backends.md
Labels: documentation

#383 update jenkins jacoco inclusionPattern
  Jenkinsfile
Labels: CI
