Repository GIScience/oshdb, pull requests merged in 2021-01, with the labels that each got.

#331 link to mentionend issues or PRs
  CHANGELOG.md
Labels: documentation

#333 oshdb text tidyup
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  config/ide/README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/manual/README.md
  documentation/manual/aggregation.md
  documentation/manual/data-model.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
  oshdb-filter/README.md
  oshdb-tool/etl/README.md
Labels: clean-up, documentation

#335 don't manipulate cluster state
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBIgnite.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestMapReduceOSHDBIgnite.java
Labels: bug

#336 fix building of multipolygon geometries with degenerate inner rings
  CHANGELOG.md
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb-util/src/test/java/org/heigit/ohsome/oshdb/util/geometry/relations/OSHDBGeometryBuilderMultipolygonInvalidInnersTest.java
  oshdb-util/src/test/resources/relations/invalid-inner-rings.osm
Labels: bug

#339 release notes for 0.6.2
  CHANGELOG.md
Labels: documentation

#344 release notes for 0.6.3
  CHANGELOG.md
Labels: documentation

#346 update main documentation to latest release
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation
