Repository GIScience/oshdb, pull requests merged in 2021-02, with the labels that each got.

#341 [oshdb-filter] also non-relations should match geometry:other
  CHANGELOG.md
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryTypeFilter.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSHTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMGeometryTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ParseTest.java
Labels: bug, waiting for review

#348 Add user survey note to README
  README.md
Labels: documentation, waiting for review

#332 clean up OSHEntities utility class
  CHANGELOG.md
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/celliterator/CellIterator.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/osh/OSHEntityTimeUtils.java
  oshdb-util/src/test/java/org/heigit/ohsome/oshdb/util/osh/TestOSHEntityTimeUtils.java
  oshdb/src/main/java/org/heigit/ohsome/oshdb/osh/OSHEntities.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHNodeTest.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHWayTest.java
Labels: code quality, unit tests, waiting for review

#352 replace unnecessary Map with a List
  CHANGELOG.md
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/celliterator/CellIterator.java
  oshdb/src/main/java/org/heigit/ohsome/oshdb/osh/OSHEntities.java
Labels: performance

#354 Jenkinsfile minor fix and clean up
  Jenkinsfile
Labels: CI, waiting for review

#353 make sure Filter predicates are always serializable
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapAggregator.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/Filter.java
Labels: user experience

#355 update link to intelliJ configuration help
  config/ide/README.md
Labels: documentation

#356 fix not-running oshdb(-core) tests
  Jenkinsfile
  oshdb/pom.xml
Labels: CI
