Repository GIScience/oshdb, pull requests merged in 2021-03, with the labels that each got.

#357 Revert "Add user survey note to README"
  README.md
Labels: waiting for review

#360 update ohsome parent to 2.8
  .idea/checkstyle-idea.xml
  CHANGELOG.md
  Jenkinsfile
  pom.xml
Labels: CI

#361 add missing clean, compile, and install goals to maven runs
  Jenkinsfile
Labels: CI

#362 catch and handle topology exceptions when splitting geometries
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/GeometrySplitter.java
Labels: bug, priority:high, waiting for review

#363 avoid tag-translating in filter optimizer, fixes crash when filters contains a non-existent tag
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducerSettings.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java
Labels: bug, waiting for review

#364 add 0.6.4 release to changelog
  CHANGELOG.md
Labels: documentation

#366 update link in documentation to release 0.6.4
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation
