Repository GIScience/oshdb, pull requests merged in 2021-04, with the labels that each got.

#368 apply the new oshdb-examples repo structure to the Jenkinsfile
  Jenkinsfile
Labels: CI

#372 configure sonarcloud
  CHANGELOG.md
  Jenkinsfile
  pom.xml
Labels: CI, code quality

#373 add SonarCloud Badge to Readme
  README.md
Labels: documentation
