Repository GIScience/oshdb, pull requests merged in 2021-08, with the labels that each got.

#411 Fix contribution-based filters used in and/or expressions
  CHANGELOG.md
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/AndOperator.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/OrOperator.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMContributionTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMEntitySnapshotTest.java
Labels: bug, priority:high

#412 specify what osm-coordinate means
  oshdb/src/main/java/org/heigit/ohsome/oshdb/OSHDBBoundingBox.java
Labels: documentation

#413 update OSHDB spelling
  CHANGELOG.md
  documentation/first-steps/README.md
  documentation/manual/installation.md
  oshdb-etl/README.md
  oshdb-filter/README.md
Labels: documentation, waiting for review

#416 change location of with-dependencies jar to the default (target) directory
  oshdb/pom.xml
Labels: CI

#417 fix serializability issue
  CHANGELOG.md
  oshdb/src/main/java/org/heigit/ohsome/oshdb/OSHDBBoundingBox.java
  oshdb/src/main/java/org/heigit/ohsome/oshdb/index/XYGridTree.java
Labels: bug, waiting for review

#418 release notes for 0.7.1 bugfix release
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  CITATION.cff
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation

#419 Some sonar-lint bugs/security hotspots
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBH2.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBJdbc.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-etl/src/main/java/org/heigit/ohsome/oshdb/tool/importer/extract/Extract.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/tagtranslator/TagTranslator.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/time/IsoDateTimeParser.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/time/TimestampFormatter.java
  oshdb-util/src/test/java/org/heigit/ohsome/oshdb/util/time/TimestampFormatterTest.java
Labels: code quality, breaking
