Repository GIScience/oshdb, pull requests merged in 2021-07, with the labels that each got.

#396 Jenkins: remove infer
  Jenkinsfile
Labels: CI

#392 Use test-compile before executing several warnings
  Jenkinsfile
  oshdb-api/pom.xml
Labels: CI

#397 OSMWay: rename getRefEntities to getMemberEntities
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/object/OSMContributionImpl.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb/src/main/java/org/heigit/ohsome/oshdb/osm/OSMRelation.java
  oshdb/src/main/java/org/heigit/ohsome/oshdb/osm/OSMWay.java
Labels: code quality

#398 Add hashEode/equals to OSHEntityImpl to match OSMEntity hashCode/equals
  oshdb/src/main/java/org/heigit/ohsome/oshdb/impl/osh/OSHEntityImpl.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHEntityTest.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHNodeTest.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java
  oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHWayTest.java
Labels: code quality, waiting for review

#399 Drop deprecated oshdb-api methods: where and osmTypes
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducerSettings.java
Labels: code quality

#400 clarify documentation of contribution view results
  CHANGELOG.md
  documentation/manual/views.md
Labels: documentation

#401 add generic OSHDBException / add ownership and cluster state check to OSHDBIgnite
  CHANGELOG.md
  oshdb-api-ignite/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBIgnite.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/exceptions/OSHDBException.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/exceptions/OSHDBInvalidTimestampException.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/exceptions/OSHDBTableNotFoundException.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/exceptions/OSHDBTagOrRoleNotFoundException.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/exceptions/OSHDBTimeoutException.java
Labels: enhancement

#305 update documentation for release 0.7.0 (and release notes)
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  README.md
  documentation/README.md
  documentation/first-steps/OSHDBApiTutorial.java
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
  oshdb-etl/README.md
Labels: documentation, waiting for review

#402 update code example to version 0.7
  README.md
Labels: documentation

#404 update ohsome-parent to version 2.12.1
  .idea/checkstyle-idea.xml
  pom.xml
Labels: dependencies

#407 bugfix incorrect bbox in GridOSHEntity.toString
  oshdb/src/main/java/org/heigit/ohsome/oshdb/grid/GridOSHEntity.java
Labels: bug

#408 Add Citation file
  CITATION.cff
Labels: comments welcome
