Repository GIScience/oshdb, pull requests merged in 2021-09, with the labels that each got.

#426 fix serializability of geometry filters
  CHANGELOG.md
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilter.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/function/SerializableToDoubleFunction.java
Labels: bug, waiting for review

#428 Bug/#427 make iterate by contribute more streamable, replace filter with takewhile
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/Kernels.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/celliterator/CellIterator.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/osh/OSHEntityTimeUtils.java
Labels: bug

#430 release notes for 0.7.2
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  CITATION.cff
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation

#431 Jenkins: update dependency cache when building
  Jenkinsfile
Labels: CI

#432 jts(1.18.2) and other dependencies plus reorganize version properties
  CHANGELOG.md
  oshdb-etl/pom.xml
  oshdb-filter/pom.xml
  oshdb-util/pom.xml
  oshdb/pom.xml
  pom.xml
Labels: dependencies
