Repository GIScience/oshdb, pull requests merged in 2022-11, with the labels that each got.

#468 add note about our handling of timestamp string parameters
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
Labels: documentation

#469 don't silently ignore invalid timestamps supplied to mapreducer
  CHANGELOG.md
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestMapReducerTimestamps.java
Labels: bug

#425 Incorrect geometry for Multipolygons with shells which share a single point
  CHANGELOG.md
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/geometry/OSHDBGeometryBuilder.java
  oshdb-util/src/test/java/org/heigit/ohsome/oshdb/util/geometry/OSHDBGeometryBuilderTest.java
  oshdb-util/src/test/java/org/heigit/ohsome/oshdb/util/geometry/OSHDBGeometryTest.java
  oshdb-util/src/test/resources/relations/multipolygonShellsShareNode.osm
Labels: bug

#436 [oshdb-filter] add additional geometry based filters
  CHANGELOG.md
  oshdb-filter/README.md
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/FilterParser.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterInnerRings.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterOuterRings.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterPerimeter.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterRoundness.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterSquareness.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/GeometryFilterVertices.java
  oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/NegatableFilter.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ApplyOSMGeometryTest.java
  oshdb-filter/src/test/java/org/heigit/ohsome/oshdb/filter/ParseTest.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/geometry/Geo.java
  oshdb-util/src/test/java/org/heigit/ohsome/oshdb/util/geometry/GeoTest.java
Labels: enhancement

#475 Suppress unnecessary warning in JdbcTagTranslator
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/tagtranslator/JdbcTagTranslator.java
Labels: code quality

#478 Move prefix as mandatory parameter in OSHDBDatabase
  CHANGELOG.md
  data/test-data-without-keytables.mv.db
  oshdb-api-ignite/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBIgnite.java
  oshdb-api-ignite/src/test/java/org/heigit/ohsome/oshdb/api/tests/MapReduceOSHDBIgniteMissingCacheTest.java
  oshdb-api-ignite/src/test/java/org/heigit/ohsome/oshdb/api/tests/MapReduceOSHDBIgniteTest.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBDatabase.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBH2.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBJdbc.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/MapReduceOSHDBJdbcMissingTablesTest.java
Labels: documentation, code quality

#473 Fix bug when calling aggregateByGeometry after a mapper is set
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestAutoAggregation.java
Labels: bug

#474 OSHDB helpers integration
  CHANGELOG.md
  documentation/first-steps/README.md
  documentation/manual/README.md
  documentation/manual/data-model.md
  documentation/manual/helpers/OSHDBApplication.md
  documentation/manual/helpers/OSHDBDriver.md
  documentation/manual/helpers/README.md
  oshdb-helpers/oshdb-application-template/pom.xml
  oshdb-helpers/oshdb-application-template/src/main/java/org/heigit/ohsome/oshdb/helpers/applicationtemplate/OSHDBApplication.java
  oshdb-helpers/oshdb-application-template/src/main/java/org/heigit/ohsome/oshdb/helpers/applicationtemplate/PropsUtil.java
  oshdb-helpers/oshdb-database-driver/pom.xml
  oshdb-helpers/oshdb-database-driver/src/main/java/org/heigit/ohsome/oshdb/helpers/db/OSHDBConnection.java
  oshdb-helpers/oshdb-database-driver/src/main/java/org/heigit/ohsome/oshdb/helpers/db/OSHDBDriver.java
  oshdb-helpers/oshdb-database-driver/src/main/java/org/heigit/ohsome/oshdb/helpers/db/Util.java
  oshdb-helpers/oshdb-database-driver/src/test/java/org/heigit/ohsome/oshdb/helpers/db/OSHDBDriverH2Test.java
  oshdb-helpers/pom.xml
  pom.xml
Labels: enhancement

#481 implement metadata for OSHDBIgnite Database
  oshdb-api-ignite/src/main/java/org/heigit/ohsome/oshdb/api/db/OSHDBIgnite.java
Labels: enhancement

#484 release notes for 1.0.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  CITATION.cff
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/geometries.md
  documentation/manual/helpers/OSHDBApplication.md
  documentation/manual/helpers/OSHDBDriver.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation
