Repository GIScience/oshdb, pull requests merged in 2023-08, with the labels that each got.

#512 bugfix: areaOfInterest should not override previously set bbox
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/OSMDataFiltersTest.java
Labels: bug, priority:low

#511 allow queries with filters to use fast-lane reducers
  CHANGELOG.md
  oshdb-api-ignite/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/MapReducerIgniteAffinityCall.java
  oshdb-api-ignite/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/MapReducerIgniteLocalPeek.java
  oshdb-api-ignite/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/MapReducerIgniteScanQuery.java
  oshdb-api-ignite/src/test/java/org/heigit/ohsome/oshdb/api/tests/MapReduceOSHDBIgniteAffinityCallTest.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/FilterFunction.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/Kernels.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/MapReducerJdbc.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/MapReducerJdbcMultithread.java
  oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/backend/MapReducerJdbcSinglethread.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/HelpersOSMContributionViewTest.java
  oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestAutoAggregation.java
  oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/mappable/OSMContribution.java
Labels: performance

#513 upgrade to ohsome parent 2.14.0
  .idea/checkstyle-idea.xml
  Jenkinsfile
  pom.xml
Labels: CI

#514 release notes for v1.2.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  CITATION.cff
  README.md
  documentation/README.md
  documentation/first-steps/README.md
  documentation/first-steps/example-pom.xml
  documentation/manual/aggregation.md
  documentation/manual/database-backends.md
  documentation/manual/filters.md
  documentation/manual/geometries.md
  documentation/manual/helpers/OSHDBApplication.md
  documentation/manual/helpers/OSHDBDriver.md
  documentation/manual/installation.md
  documentation/manual/map-reduce.md
  documentation/manual/views.md
Labels: documentation
